date,      time,           trace
13.08.2018,00:39:20.600996,bot returned response
13.08.2018,00:39:28.842207,bot returned response
13.08.2018,00:39:39.152758,bot returned response
13.08.2018,00:39:54.783616,bot returned response
13.08.2018,00:40:06.099042,bot returned response
13.08.2018,00:47:54.667406,bot returned response
13.08.2018,00:48:38.023850,bot returned response
13.08.2018,00:48:40.333421,bot returned response
13.08.2018,00:48:54.655690,bot returned response
13.08.2018,00:49:12.922293,bot returned response
13.08.2018,00:50:27.666427,bot returned response
13.08.2018,00:50:58.001389,bot returned response
13.08.2018,01:03:39.815837,bot returned response
13.08.2018,01:03:50.139083,bot returned response
13.08.2018,01:03:56.551198,bot returned response
13.08.2018,01:04:29.862715,bot returned response
13.08.2018,09:37:26.192433,bot returned response
13.08.2018,09:37:32.480527,bot returned response
13.08.2018,09:37:51.985405,bot returned response
13.08.2018,09:38:09.109430,bot returned response
13.08.2018,21:57:32.878961,bot returned response
13.08.2018,21:57:48.891651,bot returned response
13.08.2018,21:58:13.775443,bot returned response
13.08.2018,22:02:37.229550,bot returned response
14.08.2018,06:00:13.185600,bot was interrupted by error:Unable to send due to closed RTM websocket in main
14.08.2018,06:00:13.185600,bot restart attempt
14.08.2018,06:00:14.131885,bot waked up
14.08.2018,08:30:05.635794,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
14.08.2018,08:30:05.636775,bot restart attempt
14.08.2018,08:30:06.577196,bot waked up
14.08.2018,23:15:13.080119,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
14.08.2018,23:15:13.081105,bot restart attempt
14.08.2018,23:15:14.033261,bot waked up
14.08.2018,23:54:35.967815,bot returned response
14.08.2018,23:54:43.269582,bot returned response
14.08.2018,23:55:10.635792,bot returned response
14.08.2018,23:55:30.815489,bot returned response
15.08.2018,00:01:16.012741,bot waked up
15.08.2018,00:01:25.605517,bot was interrupted by error:name 'bip' is not defined in main
15.08.2018,00:01:25.606494,bot restart attempt
15.08.2018,00:01:26.319384,bot waked up
15.08.2018,00:01:52.886766,bot was interrupted by error:name 'bip' is not defined in main
15.08.2018,00:01:52.887744,bot restart attempt
15.08.2018,00:01:53.721730,bot waked up
15.08.2018,00:02:03.269579,bot returned response
15.08.2018,00:02:33.580122,bot returned response
15.08.2018,00:02:48.873094,bot returned response
15.08.2018,00:06:41.293016,bot returned response
15.08.2018,00:33:58.626999,bot waked up
15.08.2018,00:34:16.183645,bot was interrupted by error:name 'channel' is not defined in main
15.08.2018,00:34:16.185596,bot restart attempt
15.08.2018,00:34:16.925830,bot waked up
15.08.2018,00:35:40.536179,bot returned response
15.08.2018,00:35:53.836965,bot was interrupted by error:name 'channel' is not defined in main
15.08.2018,00:35:53.837943,bot restart attempt
15.08.2018,00:35:54.638724,bot waked up
15.08.2018,00:36:37.222705,bot was interrupted by error:name 'channel' is not defined in main
15.08.2018,00:36:37.223681,bot restart attempt
15.08.2018,00:36:38.026413,bot waked up
15.08.2018,00:37:14.110406,bot waked up
15.08.2018,00:37:29.023483,bot returned response
15.08.2018,00:38:23.504929,bot waked up
15.08.2018,00:38:29.070367,bot returned response
15.08.2018,00:38:50.319391,bot returned response
15.08.2018,00:39:14.627001,bot returned response
15.08.2018,00:39:26.934620,bot returned response
15.08.2018,01:52:55.590875,bot was interrupted by error:Unable to send due to closed RTM websocket in main
15.08.2018,01:52:55.590875,bot restart attempt
15.08.2018,01:52:56.469775,bot waked up
15.08.2018,22:21:44.889691,bot waked up
15.08.2018,22:22:24.468798,bot returned response
15.08.2018,22:22:38.868203,bot returned response
15.08.2018,22:23:48.408249,bot waked up
15.08.2018,22:24:00.186570,bot returned response
15.08.2018,22:31:43.795945,bot waked up
15.08.2018,22:31:52.392622,bot returned response
15.08.2018,22:32:21.165087,bot returned response
15.08.2018,22:34:19.531297,bot returned response
15.08.2018,22:34:42.826213,bot returned response
15.08.2018,22:37:42.568402,bot waked up
15.08.2018,22:38:21.122115,bot waked up
15.08.2018,22:38:29.397510,bot was interrupted by error:string indices must be integers in main
15.08.2018,22:38:29.398484,bot restart attempt
15.08.2018,22:38:30.099660,bot waked up
15.08.2018,22:46:34.973682,bot waked up
15.08.2018,22:46:45.252977,bot was interrupted by error:string indices must be integers in main
15.08.2018,22:46:45.253955,bot restart attempt
15.08.2018,22:46:45.973679,bot waked up
15.08.2018,22:47:14.188525,bot waked up
15.08.2018,22:47:19.749069,bot returned response
15.08.2018,22:48:09.491271,bot waked up
15.08.2018,22:48:17.054731,bot returned response
15.08.2018,22:54:33.777390,bot waked up
15.08.2018,22:54:43.842817,bot returned response
15.08.2018,23:40:44.446338,bot waked up
15.08.2018,23:40:57.005903,bot returned response
15.08.2018,23:41:55.810593,bot waked up
15.08.2018,23:42:02.369187,bot returned response
15.08.2018,23:47:00.427777,bot waked up
15.08.2018,23:47:07.988335,bot returned response
15.08.2018,23:51:42.396531,bot waked up
15.08.2018,23:51:48.957077,bot returned response
15.08.2018,23:51:55.271528,bot returned response
16.08.2018,00:00:33.910200,bot waked up
16.08.2018,00:12:10.638719,bot waked up
16.08.2018,00:12:23.176799,bot was interrupted by error:'channel' in main
16.08.2018,00:12:23.176799,bot restart attempt
16.08.2018,00:12:23.887742,bot waked up
16.08.2018,00:13:29.535202,bot waked up
16.08.2018,00:13:36.055716,bot was interrupted by error:'channel' in main
16.08.2018,00:13:36.056690,bot restart attempt
16.08.2018,00:13:36.769574,bot waked up
16.08.2018,00:16:54.350634,bot waked up
16.08.2018,00:17:21.877982,bot was interrupted by error:'channel' in main
16.08.2018,00:17:21.878954,bot restart attempt
16.08.2018,00:17:22.817431,bot waked up
16.08.2018,00:21:33.398489,bot waked up
16.08.2018,00:21:42.265674,bot returned response
16.08.2018,00:24:48.077195,bot waked up
16.08.2018,00:24:58.988325,bot returned response
16.08.2018,00:25:25.549849,bot waked up
16.08.2018,00:25:33.205123,bot returned response
16.08.2018,00:26:35.565510,bot waked up
16.08.2018,00:26:49.173882,bot returned response
16.08.2018,00:28:13.575239,bot waked up
16.08.2018,00:28:22.216855,bot returned response
16.08.2018,00:28:51.296935,bot waked up
16.08.2018,00:29:01.195368,bot returned response
16.08.2018,00:36:18.946332,bot waked up
16.08.2018,00:36:25.843797,bot was interrupted by error:'channel.info' in main
16.08.2018,00:36:25.844771,bot restart attempt
16.08.2018,00:36:26.559631,bot waked up
16.08.2018,00:37:09.527393,bot was interrupted by error:'channel.info' in main
16.08.2018,00:37:09.528367,bot restart attempt
16.08.2018,00:37:10.361376,bot waked up
16.08.2018,00:37:25.409226,bot returned response
16.08.2018,01:32:53.355516,bot was interrupted by error:Unable to send due to closed RTM websocket in main
16.08.2018,01:32:53.357465,bot restart attempt
16.08.2018,01:32:54.237351,bot waked up
16.08.2018,02:19:35.177779,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.08.2018,02:19:35.179726,bot restart attempt
16.08.2018,02:19:56.925834,bot failed to connect
16.08.2018,02:20:18.730526,bot failed to connect
16.08.2018,02:20:40.606495,bot failed to connect
16.08.2018,02:21:02.456099,bot failed to connect
16.08.2018,02:21:24.291063,bot failed to connect
16.08.2018,02:21:45.889697,bot failed to connect
16.08.2018,02:22:07.734422,bot failed to connect
16.08.2018,02:22:29.558645,bot failed to connect
16.08.2018,02:22:51.171921,bot failed to connect
16.08.2018,02:23:12.752983,bot failed to connect
16.08.2018,02:23:34.392625,bot failed to connect
16.08.2018,02:23:55.986374,bot failed to connect
16.08.2018,02:24:24.209043,bot failed to connect
16.08.2018,02:24:46.110403,bot failed to connect
16.08.2018,02:25:25.310590,bot failed to connect
16.08.2018,02:25:46.919971,bot failed to connect
16.08.2018,02:26:48.106501,bot failed to connect
16.08.2018,02:27:09.907274,bot failed to connect
16.08.2018,02:27:50.235403,bot waked up
17.08.2018,00:31:13.147508,bot returned response
17.08.2018,02:05:34.410202,bot was interrupted by error:Unable to send due to closed RTM websocket in main
17.08.2018,02:05:34.412149,bot restart attempt
17.08.2018,02:05:35.364305,bot waked up
17.08.2018,10:22:57.850634,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
17.08.2018,10:22:57.852582,bot restart attempt
17.08.2018,10:22:58.742230,bot waked up
18.08.2018,13:32:07.034221,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
18.08.2018,13:32:07.035199,bot restart attempt
18.08.2018,13:32:07.934627,bot waked up
19.08.2018,00:08:34.770547,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
19.08.2018,00:08:34.771524,bot restart attempt
19.08.2018,00:08:35.632856,bot waked up
20.08.2018,12:01:01.689653,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
20.08.2018,12:01:01.692583,bot restart attempt
20.08.2018,12:01:02.616408,bot waked up
20.08.2018,14:13:20.892775,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
20.08.2018,14:13:20.893757,bot restart attempt
20.08.2018,14:13:21.869337,bot waked up
20.08.2018,16:26:21.699421,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
20.08.2018,16:26:21.701367,bot restart attempt
20.08.2018,16:26:22.531446,bot waked up
20.08.2018,20:46:18.091999,bot returned response
20.08.2018,20:46:36.396681,bot returned response
20.08.2018,20:47:04.307813,bot returned response
21.08.2018,01:09:46.598827,bot was interrupted by error:Unable to send due to closed RTM websocket in main
21.08.2018,01:09:46.600779,bot restart attempt
21.08.2018,01:09:47.519725,bot waked up
22.08.2018,01:48:41.635937,bot was interrupted by error:Unable to send due to closed RTM websocket in main
22.08.2018,01:48:41.636907,bot restart attempt
09.09.2018,20:05:40.369696,bot waked up
09.09.2018,20:13:15.238834,bot waked up
09.09.2018,20:13:38.518144,bot returned response
09.09.2018,20:16:35.080641,bot waked up
09.09.2018,20:16:42.645083,bot returned response
09.09.2018,20:20:05.111887,bot returned response
09.09.2018,20:22:44.358951,bot waked up
09.09.2018,20:23:31.936103,bot returned response
09.09.2018,20:24:29.490790,bot waked up
09.09.2018,20:24:34.058176,bot returned response
09.09.2018,20:24:42.371661,bot returned response
09.09.2018,20:25:09.893138,bot returned response
09.09.2018,20:25:43.084547,bot returned response
09.09.2018,20:26:08.395091,bot returned response
09.09.2018,20:26:21.040587,bot returned response
09.09.2018,20:27:07.620670,bot returned response
09.09.2018,21:19:15.142166,bot waked up
09.09.2018,21:19:35.814031,bot returned response
09.09.2018,21:22:05.881422,bot waked up
09.09.2018,21:22:20.445866,bot returned response
09.09.2018,21:25:18.992741,bot returned response
09.09.2018,21:29:01.909750,bot waked up
09.09.2018,21:29:32.735909,bot returned response
09.09.2018,21:29:51.765208,bot returned response
09.09.2018,21:31:23.528882,bot returned response
09.09.2018,21:31:53.674384,bot waked up
09.09.2018,21:32:06.269114,bot returned response
09.09.2018,21:41:49.153878,bot waked up
09.09.2018,21:42:01.250556,bot returned response
09.09.2018,21:42:40.215402,bot waked up
09.09.2018,21:42:50.427324,bot returned response
09.09.2018,21:43:02.436102,bot waked up
09.09.2018,21:43:15.183173,bot returned response
09.09.2018,21:44:21.673413,bot waked up
09.09.2018,21:44:50.253498,bot returned response
09.09.2018,21:45:18.112863,bot waked up
09.09.2018,21:45:31.381423,bot was interrupted by error:no such group in main
09.09.2018,21:45:31.383374,bot restart attempt
09.09.2018,21:45:33.361887,bot waked up
09.09.2018,21:46:13.926337,bot waked up
09.09.2018,21:46:25.189029,bot was interrupted by error:no such group in main
09.09.2018,21:46:25.190014,bot restart attempt
09.09.2018,21:46:27.177313,bot waked up
09.09.2018,21:47:07.880440,bot waked up
09.09.2018,21:47:22.674387,bot returned response
09.09.2018,21:47:39.253486,bot returned response
09.09.2018,21:51:35.696854,bot waked up
09.09.2018,21:51:47.779854,bot returned response
09.09.2018,21:54:06.545479,bot waked up
09.09.2018,21:54:17.623609,bot returned response
09.09.2018,22:05:31.407784,bot waked up
09.09.2018,22:06:18.850161,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:06:18.851146,bot restart attempt
09.09.2018,22:06:21.105142,bot waked up
09.09.2018,22:07:24.719312,bot waked up
09.09.2018,22:07:44.156808,bot returned response
09.09.2018,22:08:27.796457,bot waked up
09.09.2018,22:08:37.420491,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:08:37.421466,bot restart attempt
09.09.2018,22:08:39.499576,bot waked up
09.09.2018,22:09:18.277900,bot returned response
09.09.2018,22:09:28.914620,bot returned response
09.09.2018,22:17:30.127510,bot waked up
09.09.2018,22:17:42.772049,bot was interrupted by error:'builtin_function_or_method' object is not subscriptable in main
09.09.2018,22:17:42.773020,bot restart attempt
09.09.2018,22:17:44.869699,bot waked up
09.09.2018,22:19:42.950750,bot waked up
09.09.2018,22:19:54.565015,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:19:54.565015,bot restart attempt
09.09.2018,22:19:56.607980,bot waked up
09.09.2018,22:23:54.535721,bot waked up
09.09.2018,22:24:05.217361,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
09.09.2018,22:24:05.218334,bot restart attempt
09.09.2018,22:24:07.240796,bot waked up
09.09.2018,22:25:26.537664,bot waked up
09.09.2018,22:25:30.857977,bot was interrupted by error:('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Неправильный синтаксис около ключевого слова "EXEC". (156) (SQLExecDirectW)') in main
09.09.2018,22:25:30.857977,bot restart attempt
09.09.2018,22:25:32.855047,bot waked up
09.09.2018,22:25:56.589423,bot waked up
09.09.2018,22:26:02.911688,bot was interrupted by error:('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Неправильный синтаксис около ключевого слова "FROM". (156) (SQLExecDirectW)') in main
09.09.2018,22:26:02.911688,bot restart attempt
09.09.2018,22:26:05.002510,bot waked up
09.09.2018,22:30:54.812079,bot waked up
09.09.2018,22:31:00.154852,bot was interrupted by error:('42000', '[42000] [Microsoft][SQL Server Native Client 11.0]Ошибка синтаксиса, отсутствие разрешения или другая неспецифическая ошибка (0) (SQLExecDirectW)') in main
09.09.2018,22:31:00.155833,bot restart attempt
09.09.2018,22:31:02.202711,bot waked up
09.09.2018,22:35:56.981030,bot waked up
09.09.2018,22:36:07.753483,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:36:07.753483,bot restart attempt
09.09.2018,22:36:09.786692,bot waked up
09.09.2018,22:43:09.758367,bot waked up
09.09.2018,22:43:23.566967,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:43:23.567945,bot restart attempt
09.09.2018,22:43:25.657787,bot waked up
09.09.2018,22:49:03.724188,bot waked up
09.09.2018,22:49:24.600167,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:49:24.600167,bot restart attempt
09.09.2018,22:49:26.498603,bot waked up
09.09.2018,22:50:45.183186,bot waked up
09.09.2018,22:51:05.092366,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:51:05.092366,bot restart attempt
09.09.2018,22:51:06.995673,bot waked up
09.09.2018,22:52:32.548409,bot waked up
09.09.2018,22:52:53.319892,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:52:53.319892,bot restart attempt
09.09.2018,22:52:55.199770,bot waked up
09.09.2018,22:56:31.275946,bot waked up
09.09.2018,22:56:41.948794,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,22:56:41.948794,bot restart attempt
09.09.2018,22:56:43.812084,bot waked up
09.09.2018,23:05:34.823806,bot waked up
09.09.2018,23:05:45.678291,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:05:45.678291,bot restart attempt
09.09.2018,23:05:47.537668,bot waked up
09.09.2018,23:06:08.445874,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:06:08.445874,bot restart attempt
09.09.2018,23:06:10.327703,bot waked up
09.09.2018,23:06:28.662665,bot waked up
09.09.2018,23:06:44.009344,bot was interrupted by error:('42000', '[42000] [Microsoft][SQL Server Native Client 11.0]Ошибка синтаксиса, отсутствие разрешения или другая неспецифическая ошибка (0) (SQLPrepare)') in main
09.09.2018,23:06:44.009344,bot restart attempt
09.09.2018,23:06:45.879464,bot waked up
09.09.2018,23:06:59.212476,bot was interrupted by error:('42000', '[42000] [Microsoft][SQL Server Native Client 11.0]Ошибка синтаксиса, отсутствие разрешения или другая неспецифическая ошибка (0) (SQLPrepare)') in main
09.09.2018,23:06:59.213450,bot restart attempt
09.09.2018,23:07:01.143136,bot waked up
09.09.2018,23:08:13.914617,bot waked up
09.09.2018,23:08:23.641182,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:08:23.641182,bot restart attempt
09.09.2018,23:08:25.499580,bot waked up
09.09.2018,23:11:13.466381,bot waked up
09.09.2018,23:11:24.260330,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:11:24.261300,bot restart attempt
09.09.2018,23:11:26.102123,bot waked up
09.09.2018,23:12:28.921455,bot waked up
09.09.2018,23:12:34.294509,bot was interrupted by error:('28000', '[28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]При входе в систему пользователя "WIN-V4AGVP6GDAV\\kkoshaev" произошла ошибка. (18456) (SQLDriverConnect); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Не удается открыть базу данных "analysis", запрашиваемую именем входа. Не удалось выполнить вход. (4060); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]При входе в систему пользователя "WIN-V4AGVP6GDAV\\kkoshaev" произошла ошибка. (18456); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Не удается открыть базу данных "analysis", запрашиваемую именем входа. Не удалось выполнить вход. (4060)') in main
09.09.2018,23:12:34.294509,bot restart attempt
09.09.2018,23:12:36.101141,bot waked up
09.09.2018,23:15:45.517159,bot waked up
09.09.2018,23:16:01.910816,bot was interrupted by error:('28000', '[28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]При входе в систему пользователя "WIN-V4AGVP6GDAV\\kkoshaev" произошла ошибка. (18456) (SQLDriverConnect); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Не удается открыть базу данных "stock_managment", запрашиваемую именем входа. Не удалось выполнить вход. (4060); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]При входе в систему пользователя "WIN-V4AGVP6GDAV\\kkoshaev" произошла ошибка. (18456); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Не удается открыть базу данных "stock_managment", запрашиваемую именем входа. Не удалось выполнить вход. (4060)') in main
09.09.2018,23:16:01.910816,bot restart attempt
09.09.2018,23:16:03.765205,bot waked up
09.09.2018,23:16:42.934150,bot waked up
09.09.2018,23:16:57.601138,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:16:57.602126,bot restart attempt
09.09.2018,23:16:59.434152,bot waked up
09.09.2018,23:32:19.676340,bot waked up
09.09.2018,23:32:37.280833,bot was interrupted by error:No results.  Previous SQL was not a query. in main
09.09.2018,23:32:37.280833,bot restart attempt
09.09.2018,23:32:39.176339,bot waked up
09.09.2018,23:32:59.983956,bot waked up
09.09.2018,23:33:21.166579,bot returned response
09.09.2018,23:33:39.112140,bot waked up
09.09.2018,23:33:56.471360,bot returned response
09.09.2018,23:34:37.114814,bot waked up
09.09.2018,23:34:57.212474,bot returned response
09.09.2018,23:38:12.737863,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
09.09.2018,23:38:12.738842,bot restart attempt
09.09.2018,23:38:14.706609,bot waked up
10.09.2018,00:05:41.822826,bot waked up
10.09.2018,00:05:58.996657,bot was interrupted by error:unsupported operand type(s) for +: 'float' and 'str' in main
10.09.2018,00:05:58.997672,bot restart attempt
10.09.2018,00:06:00.840399,bot waked up
10.09.2018,00:06:30.730055,bot was interrupted by error:unsupported operand type(s) for +: 'float' and 'str' in main
10.09.2018,00:06:30.730055,bot restart attempt
10.09.2018,00:06:32.728100,bot waked up
10.09.2018,00:06:45.753486,bot was interrupted by error:utf_8_encode() argument 1 must be str, not float in main
10.09.2018,00:06:45.753486,bot restart attempt
10.09.2018,00:06:47.671459,bot waked up
10.09.2018,00:07:13.201729,bot waked up
10.09.2018,00:07:30.381415,bot returned response
10.09.2018,00:08:49.881423,bot waked up
10.09.2018,00:09:06.655832,bot returned response
10.09.2018,00:10:37.045483,bot waked up
10.09.2018,00:11:01.945864,bot returned response
10.09.2018,00:11:23.962471,bot returned response
10.09.2018,00:16:31.751531,bot waked up
10.09.2018,00:16:48.924440,bot returned response
10.09.2018,00:31:14.427310,bot waked up
10.09.2018,00:31:34.567957,bot returned response
10.09.2018,00:32:24.792553,bot returned response
10.09.2018,00:47:08.817938,bot returned response
10.09.2018,00:47:50.183173,bot returned response
10.09.2018,00:52:28.814037,bot returned response
10.09.2018,00:54:32.580631,bot returned response
10.09.2018,00:58:49.816967,bot waked up
10.09.2018,00:59:17.387279,bot returned response
10.09.2018,00:59:22.686105,bot returned response
10.09.2018,00:59:43.318915,bot returned response
10.09.2018,01:00:05.746654,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
10.09.2018,01:00:05.746654,bot restart attempt
10.09.2018,01:00:07.760320,bot waked up
10.09.2018,01:00:39.171457,bot returned response
10.09.2018,01:00:55.888248,bot returned response
10.09.2018,15:26:09.182930,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
10.09.2018,15:26:09.182930,bot restart attempt
10.09.2018,15:26:11.364566,bot waked up
10.09.2018,18:49:30.559882,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
10.09.2018,18:49:30.560857,bot restart attempt
10.09.2018,18:49:32.722966,bot waked up
10.09.2018,23:13:16.198551,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
10.09.2018,23:13:16.199534,bot restart attempt
10.09.2018,23:13:18.304022,bot waked up
10.09.2018,23:20:52.228823,bot waked up
10.09.2018,23:21:52.303048,bot returned response
10.09.2018,23:22:29.110660,bot returned response
10.09.2018,23:28:07.039372,bot waked up
10.09.2018,23:28:57.622381,bot returned response
10.09.2018,23:38:50.837223,bot waked up
10.09.2018,23:39:10.994454,bot was interrupted by error:write() argument must be str, not float in main
10.09.2018,23:39:10.995433,bot restart attempt
10.09.2018,23:39:12.826482,bot waked up
10.09.2018,23:39:44.156557,bot was interrupted by error:write() argument must be str, not float in main
10.09.2018,23:39:44.157535,bot restart attempt
10.09.2018,23:39:46.083318,bot waked up
10.09.2018,23:43:26.814765,bot waked up
10.09.2018,23:44:08.391912,bot returned response
11.09.2018,00:07:38.323555,bot waked up
11.09.2018,00:07:56.896799,bot returned response
11.09.2018,00:08:28.852848,bot returned response
11.09.2018,00:15:26.402658,bot waked up
11.09.2018,00:15:56.964186,bot returned response
11.09.2018,00:16:44.708322,bot waked up
11.09.2018,00:18:04.297189,bot returned response
11.09.2018,00:18:41.330388,bot waked up
11.09.2018,00:19:07.674156,bot returned response
11.09.2018,00:21:11.802064,bot returned response
11.09.2018,00:23:39.533512,bot waked up
11.09.2018,00:24:23.236641,bot returned response
11.09.2018,00:52:25.451482,bot waked up
11.09.2018,00:53:09.194641,bot returned response
11.09.2018,00:53:15.534491,bot returned response
11.09.2018,00:53:22.379217,bot returned response
11.09.2018,00:53:46.081359,bot returned response
11.09.2018,00:54:34.456136,bot returned response
11.09.2018,00:55:12.390937,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
11.09.2018,00:55:12.391916,bot restart attempt
11.09.2018,00:55:14.468084,bot waked up
11.09.2018,00:55:54.648749,bot returned response
11.09.2018,06:27:04.137037,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
11.09.2018,06:27:04.138007,bot restart attempt
11.09.2018,06:27:06.136057,bot waked up
11.09.2018,15:04:43.366517,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
11.09.2018,15:04:43.368481,bot restart attempt
11.09.2018,17:05:45.147771,bot failed to connect
11.09.2018,17:05:48.175111,bot waked up
11.09.2018,19:44:33.963196,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
11.09.2018,19:44:33.965153,bot restart attempt
11.09.2018,19:44:35.959296,bot waked up
11.09.2018,23:44:01.690734,bot returned response
11.09.2018,23:44:50.716133,bot waked up
11.09.2018,23:45:24.817691,bot returned response
12.09.2018,00:12:02.974927,bot waked up
12.09.2018,00:13:34.413396,bot returned response
12.09.2018,00:17:49.493476,bot waked up
12.09.2018,00:18:24.220034,bot returned response
12.09.2018,23:07:31.763329,bot waked up
12.09.2018,23:08:43.269192,bot waked up
12.09.2018,23:22:19.519210,bot returned response
13.09.2018,00:22:21.074853,bot waked up
13.09.2018,03:50:08.467217,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
13.09.2018,03:50:08.467432,bot restart attempt
13.09.2018,03:50:10.584639,bot waked up
13.09.2018,21:25:52.465471,bot was interrupted by error:Unable to send due to closed RTM websocket in main
13.09.2018,21:25:52.466457,bot restart attempt
13.09.2018,21:25:54.305322,bot waked up
13.09.2018,21:33:37.810200,bot was interrupted by error:Unable to send due to closed RTM websocket in main
13.09.2018,21:33:37.811180,bot restart attempt
13.09.2018,21:33:39.643212,bot waked up
13.09.2018,23:34:26.894195,bot waked up
13.09.2018,23:34:59.511379,bot returned response
14.09.2018,00:16:15.281888,bot waked up
14.09.2018,00:16:29.362936,bot was interrupted by error:can only concatenate str (not "float") to str in main
14.09.2018,00:16:29.362936,bot restart attempt
14.09.2018,00:16:31.062157,bot waked up
14.09.2018,00:17:16.309225,bot waked up
14.09.2018,00:17:30.465476,bot was interrupted by error:'type' object is not subscriptable in main
14.09.2018,00:17:30.466447,bot restart attempt
14.09.2018,00:17:32.193992,bot waked up
14.09.2018,00:18:33.561179,bot waked up
14.09.2018,00:18:47.632508,bot was interrupted by error:can only concatenate str (not "float") to str in main
14.09.2018,00:18:47.632508,bot restart attempt
14.09.2018,00:18:49.346333,bot waked up
14.09.2018,00:19:20.125633,bot waked up
14.09.2018,00:21:24.813133,bot waked up
14.09.2018,00:22:22.860983,bot waked up
14.09.2018,00:22:44.024071,bot returned response
14.09.2018,00:25:22.084622,bot waked up
14.09.2018,00:29:12.116843,bot returned response
14.09.2018,00:30:21.738913,bot waked up
14.09.2018,00:30:44.586614,bot returned response
14.09.2018,00:30:56.017236,bot waked up
14.09.2018,00:31:15.374660,bot returned response
14.09.2018,00:33:23.976224,bot waked up
14.09.2018,00:33:36.116846,bot was interrupted by error:'float' object is not subscriptable in main
14.09.2018,00:33:36.116846,bot restart attempt
14.09.2018,00:33:37.820945,bot waked up
14.09.2018,00:35:59.447905,bot waked up
14.09.2018,00:36:04.530905,bot waked up
14.09.2018,00:36:24.666650,bot returned response
14.09.2018,00:39:24.529926,bot returned response
14.09.2018,14:27:41.805326,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
14.09.2018,14:27:41.806297,bot restart attempt
14.09.2018,14:27:43.684225,bot waked up
14.09.2018,17:36:58.289692,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
14.09.2018,17:36:58.291651,bot restart attempt
14.09.2018,17:37:00.304338,bot waked up
14.09.2018,20:02:21.702781,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
14.09.2018,20:02:21.702781,bot restart attempt
14.09.2018,20:02:23.628560,bot waked up
14.09.2018,22:28:18.692039,bot waked up
14.09.2018,22:28:50.616843,bot returned response
14.09.2018,22:29:25.795554,bot waked up
14.09.2018,22:30:26.829732,bot returned response
14.09.2018,22:31:44.601224,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
14.09.2018,22:31:44.601224,bot restart attempt
14.09.2018,22:31:46.486960,bot waked up
14.09.2018,22:32:14.825824,bot returned response
15.09.2018,00:08:43.587529,bot waked up
15.09.2018,00:09:12.161742,bot was interrupted by error:name 'report_date' is not defined in main
15.09.2018,00:09:12.162773,bot restart attempt
15.09.2018,00:09:13.977176,bot waked up
15.09.2018,00:10:15.372685,bot waked up
15.09.2018,00:10:27.658816,bot was interrupted by error:('22007', '[22007] [Microsoft][SQL Server Native Client 11.0][SQL Server]Ошибка преобразования даты или времени из символьной строки. (241) (SQLExecDirectW)') in main
15.09.2018,00:10:27.658816,bot restart attempt
15.09.2018,00:10:29.386357,bot waked up
15.09.2018,00:11:25.525037,bot waked up
15.09.2018,00:11:44.127565,bot was interrupted by error:('22007', '[22007] [Microsoft][SQL Server Native Client 11.0][SQL Server]Ошибка преобразования даты или времени из символьной строки. (241) (SQLExecDirectW)') in main
15.09.2018,00:11:44.127565,bot restart attempt
15.09.2018,00:11:45.847298,bot waked up
15.09.2018,00:14:09.294557,bot waked up
15.09.2018,00:14:24.910770,bot was interrupted by error:('22007', '[22007] [Microsoft][SQL Server Native Client 11.0][SQL Server]Ошибка преобразования даты или времени из символьной строки. (241) (SQLExecDirectW)') in main
15.09.2018,00:14:24.910770,bot restart attempt
15.09.2018,00:14:26.656864,bot waked up
15.09.2018,00:16:25.975225,bot waked up
15.09.2018,00:16:39.494755,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
15.09.2018,00:16:39.494755,bot restart attempt
15.09.2018,00:16:41.240848,bot waked up
15.09.2018,00:17:13.852176,bot returned response
15.09.2018,00:27:09.373662,bot waked up
15.09.2018,00:27:46.736936,bot returned response
15.09.2018,01:16:59.741821,bot waked up
15.09.2018,01:17:23.791632,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
15.09.2018,01:17:23.792605,bot restart attempt
15.09.2018,01:17:26.266236,bot waked up
15.09.2018,01:17:46.838505,bot returned response
15.09.2018,01:54:54.240849,bot returned response
15.09.2018,01:55:31.538704,bot returned response
15.09.2018,02:02:50.253538,bot returned response
15.09.2018,02:05:44.146115,bot returned response
15.09.2018,02:06:21.475223,bot returned response
15.09.2018,02:09:42.224246,bot returned response
15.09.2018,02:15:13.460583,bot returned response
15.09.2018,02:15:57.944944,bot returned response
15.09.2018,02:21:56.690070,bot returned response
15.09.2018,20:55:12.332643,bot returned response
15.09.2018,22:32:14.520146,bot waked up
15.09.2018,22:32:58.276006,bot returned response
15.09.2018,22:42:53.732057,bot waked up
15.09.2018,22:43:36.745737,bot returned response
15.09.2018,22:55:40.744752,bot returned response
16.09.2018,02:27:32.068969,bot waked up
16.09.2018,02:46:31.832653,bot waked up
16.09.2018,02:47:19.404904,bot returned response
16.09.2018,02:47:27.695925,bot returned response
16.09.2018,02:47:50.405905,bot returned response
16.09.2018,02:48:40.135377,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
16.09.2018,02:48:40.135377,bot restart attempt
16.09.2018,02:48:42.230103,bot waked up
16.09.2018,02:52:45.641237,bot was interrupted by error:('22012', '[22012] [Microsoft][SQL Server Native Client 11.0][SQL Server]Обнаружена ошибка: деление на ноль. (8134) (SQLExecDirectW)') in main
16.09.2018,02:52:45.642214,bot restart attempt
16.09.2018,02:52:47.790647,bot waked up
16.09.2018,02:53:08.008429,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,02:53:08.009410,bot restart attempt
16.09.2018,02:53:09.720343,bot waked up
16.09.2018,02:53:52.585576,bot returned response
16.09.2018,02:55:08.339486,bot returned response
16.09.2018,02:56:47.688117,bot returned response
16.09.2018,02:57:29.808239,bot returned response
16.09.2018,02:58:05.122684,bot returned response
16.09.2018,03:18:58.495728,bot waked up
16.09.2018,03:21:00.732062,bot waked up
16.09.2018,03:22:17.425418,bot waked up
16.09.2018,03:22:48.034793,bot returned response
16.09.2018,03:23:16.124631,bot returned response
16.09.2018,03:23:41.922488,bot returned response
16.09.2018,03:24:02.577763,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,03:24:02.577763,bot restart attempt
16.09.2018,03:24:04.475231,bot waked up
16.09.2018,03:26:19.645143,bot returned response
16.09.2018,03:26:36.344362,bot returned response
16.09.2018,03:34:44.890263,bot returned response
16.09.2018,03:53:14.940063,bot waked up
16.09.2018,03:53:54.345346,bot returned response
16.09.2018,03:54:09.916628,bot waked up
16.09.2018,03:54:17.183231,bot was interrupted by error:module 'cnf' has no attribute 'OUTPUT_FILE_NAME1' in main
16.09.2018,03:54:17.184206,bot restart attempt
16.09.2018,03:54:18.901012,bot waked up
16.09.2018,03:54:59.182250,bot was interrupted by error:module 'cnf' has no attribute 'OUTPUT_FILE_NAME1' in main
16.09.2018,03:54:59.183250,bot restart attempt
16.09.2018,03:55:01.086545,bot waked up
16.09.2018,03:55:30.597297,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,03:55:30.598292,bot restart attempt
16.09.2018,03:55:32.470338,bot waked up
16.09.2018,03:56:31.646125,bot returned response
16.09.2018,04:00:12.103150,bot waked up
16.09.2018,04:00:17.651008,bot returned response
16.09.2018,04:00:32.719369,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,04:00:32.719369,bot restart attempt
16.09.2018,04:00:34.460577,bot waked up
16.09.2018,04:00:55.217404,bot returned response
16.09.2018,04:01:25.002561,bot returned response
16.09.2018,04:01:50.314090,bot returned response
16.09.2018,11:34:29.863031,bot returned response
16.09.2018,11:34:37.153100,bot returned response
16.09.2018,11:34:54.357171,bot returned response
16.09.2018,11:35:38.353268,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,11:35:38.354243,bot restart attempt
16.09.2018,11:35:40.177493,bot waked up
16.09.2018,11:36:50.325922,bot returned response
16.09.2018,12:53:41.194084,bot returned response
16.09.2018,14:32:32.449945,bot waked up
16.09.2018,14:33:11.148181,bot returned response
16.09.2018,14:37:02.690177,bot waked up
16.09.2018,14:37:58.966553,bot returned response
16.09.2018,14:44:54.630609,bot returned response
16.09.2018,14:45:38.474359,bot waked up
16.09.2018,14:46:00.237121,bot returned response
16.09.2018,14:47:37.325921,bot waked up
16.09.2018,14:48:16.014654,bot returned response
16.09.2018,14:49:02.424556,bot waked up
16.09.2018,14:49:20.528068,bot returned response
16.09.2018,15:27:22.879628,bot waked up
16.09.2018,15:32:05.453853,bot waked up
16.09.2018,15:39:18.687247,bot waked up
16.09.2018,15:41:03.124750,bot waked up
16.09.2018,15:41:26.681385,bot returned response
16.09.2018,15:45:18.781981,bot waked up
16.09.2018,15:45:45.442132,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,15:45:45.443110,bot restart attempt
16.09.2018,15:45:47.229240,bot waked up
16.09.2018,15:46:29.670648,bot returned response
16.09.2018,15:52:32.477293,bot waked up
16.09.2018,15:53:01.227286,bot returned response
16.09.2018,15:53:52.662834,bot waked up
16.09.2018,15:54:16.631585,bot returned response
16.09.2018,15:56:04.295652,bot waked up
16.09.2018,15:56:24.431391,bot returned response
16.09.2018,15:57:44.119867,bot waked up
16.09.2018,15:58:07.650149,bot returned response
16.09.2018,15:59:07.834714,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,15:59:07.835687,bot restart attempt
16.09.2018,15:59:09.720462,bot waked up
16.09.2018,16:01:16.055409,bot waked up
16.09.2018,16:01:49.282958,bot was interrupted by error:local variable 'parameter' referenced before assignment in main
16.09.2018,16:01:49.282958,bot restart attempt
16.09.2018,16:01:51.145275,bot waked up
16.09.2018,16:02:28.045646,bot waked up
16.09.2018,16:02:50.809354,bot returned response
16.09.2018,16:05:40.682364,bot waked up
16.09.2018,16:06:07.139397,bot returned response
16.09.2018,16:07:05.554438,bot returned response
16.09.2018,16:08:53.270259,bot waked up
16.09.2018,16:09:24.015383,bot returned response
16.09.2018,16:10:51.374747,bot waked up
16.09.2018,16:11:19.120840,bot returned response
16.09.2018,16:11:45.809315,bot returned response
16.09.2018,16:58:44.632561,bot returned response
16.09.2018,17:01:38.810296,bot returned response
16.09.2018,17:02:13.029045,bot returned response
16.09.2018,17:08:38.742914,bot returned response
16.09.2018,17:23:17.540766,bot returned response
16.09.2018,17:23:55.834712,bot returned response
16.09.2018,17:24:39.153065,bot returned response
16.09.2018,17:24:56.906978,bot returned response
16.09.2018,20:41:26.072021,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.09.2018,20:41:26.072992,bot restart attempt
16.09.2018,20:41:27.948980,bot waked up
16.09.2018,21:27:27.753656,bot returned response
16.09.2018,21:28:17.332754,bot was interrupted by error:local variable 'result' referenced before assignment in main
16.09.2018,21:28:17.333737,bot restart attempt
16.09.2018,21:28:20.130608,bot waked up
16.09.2018,21:28:34.629631,bot returned response
17.09.2018,00:23:27.379631,bot returned response
17.09.2018,05:55:47.047238,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
17.09.2018,05:55:47.048223,bot restart attempt
17.09.2018,05:55:48.946661,bot waked up
20.09.2018,14:23:38.100947,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
20.09.2018,14:23:38.100947,bot restart attempt
20.09.2018,14:23:40.518918,bot waked up
20.09.2018,17:09:58.326534,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
20.09.2018,17:09:58.327507,bot restart attempt
20.09.2018,17:10:00.221066,bot waked up
21.09.2018,15:15:56.546265,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
21.09.2018,15:15:56.547255,bot restart attempt
21.09.2018,15:15:58.606809,bot waked up
22.09.2018,01:52:44.243527,bot returned response
22.09.2018,01:53:21.405632,bot returned response
22.09.2018,01:53:37.216179,bot returned response
08.10.2018,22:14:38.113096,bot waked up
08.10.2018,22:15:02.724422,bot returned response
08.10.2018,22:15:09.021291,bot returned response
08.10.2018,22:15:42.823051,bot returned response
08.10.2018,22:38:57.432428,bot waked up
08.10.2018,22:53:17.692194,bot waked up
08.10.2018,22:54:51.354297,bot waked up
08.10.2018,22:54:54.907040,bot returned response
08.10.2018,22:55:16.420710,bot returned response
08.10.2018,22:59:05.136543,bot waked up
08.10.2018,23:00:05.847510,bot returned response
08.10.2018,23:02:53.287894,bot waked up
08.10.2018,23:03:16.352350,bot returned response
08.10.2018,23:05:26.287896,bot waked up
08.10.2018,23:08:20.152163,bot waked up
08.10.2018,23:19:50.506646,bot waked up
08.10.2018,23:20:09.247858,bot returned response
08.10.2018,23:20:33.438291,bot returned response
08.10.2018,23:21:04.994924,bot returned response
08.10.2018,23:23:26.360162,bot returned response
08.10.2018,23:23:33.659967,bot returned response
08.10.2018,23:23:51.768366,bot returned response
08.10.2018,23:24:14.751765,bot returned response
08.10.2018,23:24:30.266411,bot was interrupted by error:local variable 'result' referenced before assignment in main
08.10.2018,23:24:30.266411,bot restart attempt
08.10.2018,23:24:32.249828,bot waked up
08.10.2018,23:24:53.824031,bot returned response
08.10.2018,23:25:04.147265,bot returned response
08.10.2018,23:25:27.003719,bot was interrupted by error:local variable 'result' referenced before assignment in main
08.10.2018,23:25:27.004696,bot restart attempt
08.10.2018,23:25:28.917780,bot waked up
08.10.2018,23:27:13.795707,bot was interrupted by error:local variable 'result' referenced before assignment in main
08.10.2018,23:27:13.796687,bot restart attempt
08.10.2018,23:27:15.665834,bot waked up
08.10.2018,23:27:54.722468,bot returned response
09.10.2018,07:24:16.176561,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.10.2018,07:24:16.176561,bot restart attempt
09.10.2018,07:24:17.966605,bot waked up
09.10.2018,09:34:50.968565,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.10.2018,09:34:50.969538,bot restart attempt
09.10.2018,09:34:52.898245,bot waked up
09.10.2018,12:12:58.837695,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.10.2018,12:12:58.837695,bot restart attempt
09.10.2018,12:13:00.630671,bot waked up
09.10.2018,21:01:00.136530,bot waked up
09.10.2018,23:33:03.575979,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.10.2018,23:33:03.576957,bot restart attempt
09.10.2018,23:33:05.523243,bot waked up
10.10.2018,00:14:23.160940,bot waked up
10.10.2018,00:14:48.716603,bot returned response
10.10.2018,00:15:31.137505,bot waked up
10.10.2018,00:15:37.721490,bot returned response
10.10.2018,00:15:45.460757,bot was interrupted by error:tuple index out of range in main
10.10.2018,00:15:45.460757,bot restart attempt
10.10.2018,00:15:47.243948,bot waked up
10.10.2018,00:17:33.589655,bot waked up
10.10.2018,00:17:50.933419,bot returned response
10.10.2018,00:21:22.408013,bot waked up
10.10.2018,00:21:36.984190,bot returned response
10.10.2018,00:21:57.795300,bot returned response
10.10.2018,00:22:19.523244,bot was interrupted by error:local variable 'result' referenced before assignment in main
10.10.2018,00:22:19.524221,bot restart attempt
10.10.2018,00:22:21.411918,bot waked up
10.10.2018,00:22:54.163874,bot returned response
10.10.2018,00:23:16.709772,bot returned response
10.10.2018,00:24:28.230271,bot waked up
10.10.2018,00:24:39.228331,bot returned response
10.10.2018,00:25:06.757617,bot returned response
10.10.2018,00:25:29.159958,bot returned response
10.10.2018,00:25:57.175596,bot returned response
11.10.2018,22:26:08.897264,bot waked up
11.10.2018,22:32:43.770316,bot returned response
11.10.2018,23:13:49.911912,bot waked up
11.10.2018,23:14:11.518359,bot returned response
11.10.2018,23:14:35.086711,bot returned response
11.10.2018,23:16:10.653121,bot returned response
11.10.2018,23:16:45.555468,bot was interrupted by error:local variable 'result' referenced before assignment in main
11.10.2018,23:16:45.556458,bot restart attempt
11.10.2018,23:16:47.507618,bot waked up
11.10.2018,23:17:34.179490,bot returned response
12.10.2018,00:24:01.052541,bot waked up
12.10.2018,00:24:12.708792,bot was interrupted by error:can only concatenate str (not "pyodbc.Row") to str in main
12.10.2018,00:24:12.708792,bot restart attempt
12.10.2018,00:24:14.463673,bot waked up
12.10.2018,00:24:43.123827,bot was interrupted by error:can only concatenate str (not "pyodbc.Row") to str in main
12.10.2018,00:24:43.124813,bot restart attempt
12.10.2018,00:24:44.972473,bot waked up
12.10.2018,00:26:13.053507,bot waked up
12.10.2018,00:26:17.769347,bot returned response
12.10.2018,00:27:20.209765,bot returned response
12.10.2018,00:34:46.350397,bot returned response
12.10.2018,00:38:29.092574,bot waked up
12.10.2018,00:38:44.733202,bot returned response
12.10.2018,00:39:42.800587,bot waked up
12.10.2018,00:39:49.435350,bot returned response
12.10.2018,00:40:22.509571,bot waked up
12.10.2018,00:40:28.153176,bot returned response
12.10.2018,00:40:37.480272,bot returned response
12.10.2018,00:46:09.553513,bot waked up
12.10.2018,00:46:16.195117,bot returned response
12.10.2018,00:47:07.808396,bot returned response
12.10.2018,00:47:16.432421,bot returned response
12.10.2018,00:51:16.211717,bot waked up
12.10.2018,01:13:40.831833,bot waked up
12.10.2018,01:13:52.426562,bot returned response
12.10.2018,01:14:09.882616,bot returned response
12.10.2018,19:56:55.190241,bot was interrupted by error:Unable to send due to closed RTM websocket in main
12.10.2018,19:56:55.191213,bot restart attempt
12.10.2018,19:56:57.124807,bot waked up
12.10.2018,20:08:02.038863,bot was interrupted by error:Unable to send due to closed RTM websocket in main
12.10.2018,20:08:02.039846,bot restart attempt
12.10.2018,20:08:03.840623,bot waked up
12.10.2018,22:22:43.994914,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
12.10.2018,22:22:43.995898,bot restart attempt
12.10.2018,22:22:45.956834,bot waked up
15.10.2018,20:57:35.723147,bot waked up
15.10.2018,20:58:03.199709,bot returned response
15.10.2018,21:01:13.062012,bot waked up
15.10.2018,21:02:00.062040,bot waked up
15.10.2018,21:41:41.494632,bot waked up
15.10.2018,21:42:25.331544,bot waked up
15.10.2018,21:43:02.934087,bot waked up
15.10.2018,21:45:16.534672,bot waked up
15.10.2018,21:46:38.722174,bot waked up
15.10.2018,21:48:41.997563,bot waked up
15.10.2018,21:53:28.867679,bot waked up
15.10.2018,21:58:17.664562,bot waked up
15.10.2018,22:10:33.829587,bot waked up
15.10.2018,22:19:33.167499,bot waked up
15.10.2018,22:19:55.075703,bot waked up
15.10.2018,22:20:15.769065,bot waked up
15.10.2018,22:20:45.788577,bot waked up
15.10.2018,22:22:29.480965,bot waked up
15.10.2018,22:22:47.219235,bot waked up
15.10.2018,22:35:32.519044,bot waked up
15.10.2018,22:35:41.133323,bot returned response
15.10.2018,22:35:55.438956,bot returned response
15.10.2018,22:36:44.767093,bot returned response
15.10.2018,22:39:41.825679,bot waked up
15.10.2018,22:39:51.387206,bot returned response
15.10.2018,22:40:26.720214,bot returned response
15.10.2018,22:41:59.812005,bot waked up
15.10.2018,22:42:17.445801,bot returned response
15.10.2018,22:48:08.724283,bot waked up
15.10.2018,22:48:18.314956,bot returned response
15.10.2018,22:48:28.626467,bot returned response
15.10.2018,22:48:42.931153,bot returned response
15.10.2018,22:49:21.839361,bot waked up
15.10.2018,22:49:29.422365,bot returned response
15.10.2018,22:49:54.742678,bot returned response
15.10.2018,22:50:08.048339,bot returned response
15.10.2018,22:50:36.437988,bot returned response
15.10.2018,22:55:27.985862,bot waked up
15.10.2018,22:55:47.908688,bot returned response
15.10.2018,22:56:18.559082,bot returned response
15.10.2018,23:01:31.127438,bot returned response
15.10.2018,23:04:47.017091,bot waked up
15.10.2018,23:05:23.887207,bot returned response
15.10.2018,23:05:43.581538,bot waked up
15.10.2018,23:05:59.455568,bot returned response
15.10.2018,23:06:16.835450,bot waked up
15.10.2018,23:06:27.692869,bot returned response
15.10.2018,23:06:53.377456,bot waked up
15.10.2018,23:07:04.101078,bot was interrupted by error:can only concatenate list (not "str") to list in main
15.10.2018,23:07:04.101078,bot restart attempt
15.10.2018,23:07:06.011234,bot waked up
15.10.2018,23:08:43.319831,bot waked up
15.10.2018,23:08:54.921384,bot was interrupted by error:can only join an iterable in main
15.10.2018,23:08:54.921384,bot restart attempt
15.10.2018,23:08:56.670412,bot waked up
15.10.2018,23:14:57.539550,bot waked up
15.10.2018,23:15:17.404788,bot returned response
15.10.2018,23:17:23.326684,bot waked up
15.10.2018,23:17:36.191893,bot returned response
15.10.2018,23:18:43.737805,bot waked up
15.10.2018,23:18:54.305187,bot was interrupted by error:name 'region_asStr' is not defined in main
15.10.2018,23:18:54.305187,bot restart attempt
15.10.2018,23:18:56.076680,bot waked up
15.10.2018,23:21:23.370609,bot waked up
15.10.2018,23:21:35.952639,bot returned response
15.10.2018,23:21:54.540524,bot returned response
15.10.2018,23:22:01.841302,bot returned response
15.10.2018,23:22:08.135252,bot returned response
15.10.2018,23:22:17.754397,bot returned response
15.10.2018,23:22:40.063968,bot returned response
15.10.2018,23:23:06.753427,bot returned response
15.10.2018,23:27:21.940916,bot waked up
15.10.2018,23:27:31.542479,bot returned response
15.10.2018,23:27:39.853028,bot returned response
15.10.2018,23:28:15.874579,bot returned response
15.10.2018,23:28:51.000488,bot waked up
15.10.2018,23:29:13.344238,bot returned response
15.10.2018,23:29:31.692872,bot returned response
15.10.2018,23:29:42.291500,bot returned response
15.10.2018,23:29:57.624512,bot returned response
15.10.2018,23:30:05.946774,bot returned response
15.10.2018,23:30:19.546417,bot returned response
15.10.2018,23:30:32.155764,bot returned response
15.10.2018,23:31:05.799322,bot returned response
15.10.2018,23:32:36.925328,bot waked up
15.10.2018,23:32:47.176270,bot was interrupted by error:local variable 'result' referenced before assignment in main
15.10.2018,23:32:47.177256,bot restart attempt
15.10.2018,23:32:48.965336,bot waked up
15.10.2018,23:33:17.529795,bot returned response
15.10.2018,23:34:16.302246,bot returned response
15.10.2018,23:34:43.852104,bot returned response
15.10.2018,23:35:08.517085,bot waked up
15.10.2018,23:35:36.353999,bot returned response
15.10.2018,23:35:51.838378,bot returned response
15.10.2018,23:36:07.434081,bot returned response
15.10.2018,23:36:21.476072,bot waked up
15.10.2018,23:37:25.036625,bot waked up
15.10.2018,23:37:32.660646,bot returned response
15.10.2018,23:37:47.979002,bot returned response
15.10.2018,23:37:59.947755,bot returned response
15.10.2018,23:40:04.061035,bot waked up
15.10.2018,23:40:26.653807,bot returned response
15.10.2018,23:40:41.969237,bot returned response
15.10.2018,23:40:56.340344,bot returned response
15.10.2018,23:46:15.891111,bot returned response
15.10.2018,23:46:25.239764,bot returned response
15.10.2018,23:46:52.424318,bot returned response
15.10.2018,23:47:02.738767,bot returned response
15.10.2018,23:47:34.060053,bot returned response
15.10.2018,23:47:44.358889,bot returned response
15.10.2018,23:47:54.783690,bot returned response
15.10.2018,23:53:31.270029,bot waked up
15.10.2018,23:53:41.848157,bot returned response
15.10.2018,23:54:46.176266,bot returned response
15.10.2018,23:54:57.500499,bot returned response
15.10.2018,23:55:18.859865,bot returned response
15.10.2018,23:55:39.204590,bot returned response
15.10.2018,23:56:23.417491,bot waked up
15.10.2018,23:56:35.001464,bot returned response
15.10.2018,23:59:36.470215,bot returned response
16.10.2018,00:15:09.090327,bot waked up
16.10.2018,00:15:21.662596,bot returned response
16.10.2018,00:15:37.298429,bot returned response
16.10.2018,02:29:58.276851,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,02:29:58.276851,bot restart attempt
16.10.2018,02:30:00.341318,bot waked up
16.10.2018,04:48:21.693849,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,04:48:21.693849,bot restart attempt
16.10.2018,04:48:23.815915,bot waked up
16.10.2018,06:55:13.763178,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,06:55:13.763178,bot restart attempt
16.10.2018,06:55:15.666502,bot waked up
16.10.2018,09:21:30.322758,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,09:21:30.322758,bot restart attempt
16.10.2018,09:21:32.277832,bot waked up
16.10.2018,15:43:44.003409,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,15:43:44.003409,bot restart attempt
16.10.2018,15:43:45.923341,bot waked up
16.10.2018,18:09:52.554195,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
16.10.2018,18:09:52.554195,bot restart attempt
16.10.2018,18:09:54.436044,bot waked up
17.10.2018,15:45:29.890138,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
17.10.2018,15:45:29.890138,bot restart attempt
17.10.2018,15:45:36.014166,bot waked up
18.10.2018,18:01:00.150878,bot was interrupted by error:Unable to send due to closed RTM websocket in main
18.10.2018,18:01:00.151862,bot restart attempt
18.10.2018,18:01:02.300585,bot waked up
18.10.2018,20:53:06.937002,bot was interrupted by error:Unable to send due to closed RTM websocket in main
18.10.2018,20:53:06.937985,bot restart attempt
18.10.2018,20:53:07.880374,bot waked up
23.10.2018,20:06:48.938601,bot waked up
23.10.2018,20:07:25.065556,bot returned response
23.10.2018,20:43:42.665166,bot waked up
23.10.2018,20:46:13.012833,bot waked up
23.10.2018,20:47:47.631964,bot waked up
23.10.2018,20:48:12.697428,bot waked up
23.10.2018,20:48:26.559693,bot was interrupted by error:tuple index out of range in main
23.10.2018,20:48:26.559693,bot restart attempt
23.10.2018,20:48:27.354628,bot waked up
23.10.2018,20:49:58.463016,bot waked up
23.10.2018,20:50:07.339981,bot was interrupted by error:tuple index out of range in main
23.10.2018,20:50:07.340956,bot restart attempt
23.10.2018,20:50:08.101693,bot waked up
23.10.2018,20:54:48.023563,bot waked up
23.10.2018,20:55:46.785287,bot returned response
23.10.2018,20:56:06.155399,bot returned response
23.10.2018,20:56:15.748177,bot was interrupted by error:tuple index out of range in main
23.10.2018,20:56:15.748177,bot restart attempt
23.10.2018,20:56:16.728648,bot waked up
23.10.2018,20:57:43.764780,bot waked up
23.10.2018,20:58:07.461063,bot returned response
23.10.2018,21:12:42.774542,bot waked up
23.10.2018,21:13:05.546024,bot returned response
23.10.2018,21:13:48.852664,bot was interrupted by error:[Errno 2] No such file or directory: 'C:\\Users\\kkoshaev\\Downloads\\23.10.2018Регион 10region_treemap.png' in main
23.10.2018,21:13:48.852664,bot restart attempt
23.10.2018,21:13:49.760869,bot waked up
23.10.2018,21:21:19.909310,bot was interrupted by error:[Errno 2] No such file or directory: 'C:\\Users\\kkoshaev\\Downloads\\23.10.2018Регион 10region_treemap.png' in main
23.10.2018,21:21:19.909310,bot restart attempt
23.10.2018,21:21:20.908332,bot waked up
23.10.2018,21:36:17.938603,bot waked up
23.10.2018,21:36:40.838023,bot returned response
23.10.2018,21:38:40.791136,bot waked up
23.10.2018,21:41:29.802863,bot waked up
23.10.2018,21:41:50.936663,bot returned response
23.10.2018,21:44:44.767712,bot waked up
23.10.2018,21:45:29.067510,bot returned response
23.10.2018,21:48:31.908338,bot returned response
23.10.2018,21:48:50.539182,bot returned response
23.10.2018,21:53:41.563603,bot waked up
23.10.2018,21:54:06.723754,bot returned response
23.10.2018,21:54:56.464011,bot waked up
23.10.2018,21:55:21.139775,bot returned response
23.10.2018,21:55:46.525523,bot waked up
23.10.2018,21:56:07.168097,bot returned response
23.10.2018,21:56:30.222786,bot returned response
23.10.2018,21:58:13.055794,bot returned response
23.10.2018,22:02:18.955208,bot waked up
23.10.2018,22:02:31.941534,bot was interrupted by error:name 'asgs' is not defined in main
23.10.2018,22:02:31.941534,bot restart attempt
23.10.2018,22:02:32.702274,bot waked up
23.10.2018,22:02:57.812635,bot waked up
23.10.2018,22:05:29.702271,bot waked up
23.10.2018,22:07:11.869271,bot waked up
23.10.2018,22:08:26.302861,bot waked up
23.10.2018,22:09:36.515746,bot waked up
23.10.2018,22:09:58.350710,bot returned response
23.10.2018,22:12:43.553838,bot waked up
23.10.2018,22:13:45.280398,bot waked up
23.10.2018,22:14:18.945438,bot returned response
23.10.2018,22:14:43.967907,bot returned response
23.10.2018,22:19:31.210083,bot waked up
23.10.2018,22:21:09.843878,bot waked up
23.10.2018,22:21:41.104615,bot returned response
23.10.2018,22:21:58.793090,bot was interrupted by error:list index out of range in main
23.10.2018,22:21:58.793090,bot restart attempt
23.10.2018,22:21:59.645636,bot waked up
23.10.2018,22:25:46.672982,bot waked up
23.10.2018,22:26:05.233526,bot was interrupted by error:[Errno 2] No such file or directory: 'C:\\Users\\kkoshaev\\Downloads\\23.10.2018Регион 30region_treemap.png' in main
23.10.2018,22:26:05.233526,bot restart attempt
23.10.2018,22:26:06.006969,bot waked up
23.10.2018,22:26:53.603646,bot waked up
23.10.2018,22:27:15.768683,bot returned response
23.10.2018,22:27:52.095828,bot returned response
23.10.2018,22:28:02.448372,bot returned response
23.10.2018,22:28:10.745244,bot returned response
23.10.2018,22:28:18.376103,bot returned response
23.10.2018,22:32:03.086068,bot returned response
23.10.2018,22:33:18.377074,bot returned response
23.10.2018,22:34:55.236451,bot returned response
23.10.2018,22:35:37.613402,bot waked up
23.10.2018,22:35:47.156378,bot returned response
23.10.2018,22:36:03.933722,bot returned response
23.10.2018,22:37:11.381958,bot was interrupted by error:local variable 'result' referenced before assignment in main
23.10.2018,22:37:11.382936,bot restart attempt
23.10.2018,22:37:12.205205,bot waked up
23.10.2018,22:37:23.781374,bot returned response
23.10.2018,22:37:39.232553,bot was interrupted by error:local variable 'result' referenced before assignment in main
23.10.2018,22:37:39.233530,bot restart attempt
23.10.2018,22:37:40.014777,bot waked up
23.10.2018,22:39:26.958132,bot returned response
23.10.2018,22:40:28.919067,bot returned response
23.10.2018,22:42:59.688609,bot returned response
23.10.2018,22:58:33.255010,bot waked up
23.10.2018,22:59:08.173957,bot returned response
23.10.2018,23:00:27.712043,bot waked up
23.10.2018,23:00:50.860478,bot returned response
23.10.2018,23:02:24.697404,bot waked up
23.10.2018,23:02:52.561661,bot returned response
23.10.2018,23:03:00.876101,bot returned response
23.10.2018,23:03:29.384890,bot returned response
23.10.2018,23:04:05.628056,bot returned response
23.10.2018,23:04:59.201300,bot returned response
23.10.2018,23:05:07.515752,bot returned response
23.10.2018,23:05:18.822391,bot returned response
23.10.2018,23:05:25.159300,bot returned response
23.10.2018,23:05:35.756973,bot returned response
23.10.2018,23:05:48.086060,bot was interrupted by error:local variable 'result' referenced before assignment in main
23.10.2018,23:05:48.086060,bot restart attempt
23.10.2018,23:05:48.905415,bot waked up
23.10.2018,23:07:57.491336,bot waked up
23.10.2018,23:08:11.856573,bot was interrupted by error:local variable 'result' referenced before assignment in main
23.10.2018,23:08:11.857553,bot restart attempt
23.10.2018,23:08:12.683727,bot waked up
23.10.2018,23:08:45.261845,bot returned response
23.10.2018,23:09:11.712181,bot returned response
23.10.2018,23:11:46.404425,bot returned response
23.10.2018,23:35:42.032353,bot waked up
23.10.2018,23:36:35.788207,bot returned response
23.10.2018,23:36:55.329232,bot returned response
23.10.2018,23:38:21.866342,bot returned response
23.10.2018,23:41:09.076294,bot was interrupted by error:local variable 'result' referenced before assignment in main
23.10.2018,23:41:09.076294,bot restart attempt
23.10.2018,23:41:09.857548,bot waked up
23.10.2018,23:41:30.636859,bot returned response
23.10.2018,23:41:42.323361,bot returned response
24.10.2018,01:55:32.342900,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
24.10.2018,01:55:32.343875,bot restart attempt
24.10.2018,01:55:33.212072,bot waked up
24.10.2018,06:46:06.715949,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
24.10.2018,06:46:06.716925,bot restart attempt
24.10.2018,06:46:08.457153,bot waked up
24.10.2018,07:33:10.723761,bot returned response
24.10.2018,07:33:21.038212,bot returned response
24.10.2018,07:33:23.324347,bot returned response
24.10.2018,07:33:40.909305,bot returned response
24.10.2018,07:34:18.625131,bot returned response
24.10.2018,07:59:49.630004,bot was interrupted by error:local variable 'result' referenced before assignment in main
24.10.2018,07:59:49.630981,bot restart attempt
24.10.2018,07:59:50.507939,bot waked up
24.10.2018,08:00:09.934698,bot was interrupted by error:local variable 'result' referenced before assignment in main
24.10.2018,08:00:09.934698,bot restart attempt
24.10.2018,08:00:10.660290,bot waked up
24.10.2018,10:54:31.335091,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
24.10.2018,10:54:31.335091,bot restart attempt
24.10.2018,10:54:32.432742,bot waked up
24.10.2018,11:48:48.867314,bot returned response
24.10.2018,11:49:17.864386,bot returned response
25.10.2018,02:02:54.779413,bot was interrupted by error:Unable to send due to closed RTM websocket in main
25.10.2018,02:02:54.780399,bot restart attempt
25.10.2018,02:02:55.655406,bot waked up
25.10.2018,04:26:23.200314,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,04:26:23.200314,bot restart attempt
25.10.2018,04:26:24.175907,bot waked up
25.10.2018,07:18:22.725704,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,07:18:22.726685,bot restart attempt
25.10.2018,07:18:23.610475,bot waked up
25.10.2018,09:29:04.813592,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,09:29:04.814572,bot restart attempt
25.10.2018,09:29:05.780405,bot waked up
25.10.2018,11:48:16.240354,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,11:48:16.241338,bot restart attempt
25.10.2018,11:48:17.117306,bot waked up
25.10.2018,15:17:03.235470,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,15:17:03.236452,bot restart attempt
25.10.2018,15:17:04.305780,bot waked up
25.10.2018,18:23:29.312624,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,18:23:29.313603,bot restart attempt
25.10.2018,18:23:30.297021,bot waked up
25.10.2018,19:44:01.646606,bot returned response
25.10.2018,19:54:52.352668,bot waked up
25.10.2018,19:55:10.962037,bot was interrupted by error:name 'lsit' is not defined in main
25.10.2018,19:55:10.962037,bot restart attempt
25.10.2018,19:55:11.765742,bot waked up
25.10.2018,19:55:32.009889,bot waked up
25.10.2018,19:55:40.567515,bot was interrupted by error:'list' object is not callable in main
25.10.2018,19:55:40.567515,bot restart attempt
25.10.2018,19:55:41.357547,bot waked up
25.10.2018,19:57:44.126367,bot waked up
25.10.2018,19:57:51.675904,bot returned response
25.10.2018,19:58:03.275511,bot returned response
25.10.2018,19:58:38.587031,bot returned response
25.10.2018,19:58:47.207150,bot returned response
25.10.2018,19:59:23.515740,bot returned response
25.10.2018,19:59:43.143679,bot returned response
25.10.2018,22:28:23.636843,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
25.10.2018,22:28:23.637814,bot restart attempt
25.10.2018,22:28:24.518684,bot waked up
26.10.2018,08:11:14.570433,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
26.10.2018,08:11:14.571411,bot restart attempt
26.10.2018,08:11:15.463013,bot waked up
26.10.2018,20:31:24.128045,bot returned response
26.10.2018,20:31:42.195431,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,20:31:42.196418,bot restart attempt
26.10.2018,20:31:43.164186,bot waked up
26.10.2018,20:31:57.489379,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,20:31:57.490373,bot restart attempt
26.10.2018,20:31:58.273563,bot waked up
26.10.2018,20:32:17.934687,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,20:32:17.934687,bot restart attempt
26.10.2018,20:32:18.769686,bot waked up
26.10.2018,20:32:53.532347,bot returned response
26.10.2018,20:33:20.326292,bot returned response
26.10.2018,20:34:40.448361,bot returned response
26.10.2018,20:35:10.870238,bot returned response
26.10.2018,20:35:34.036252,bot returned response
26.10.2018,20:35:51.256962,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,20:35:51.256962,bot restart attempt
26.10.2018,20:35:52.207161,bot waked up
26.10.2018,20:42:01.846795,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,20:42:01.846795,bot restart attempt
26.10.2018,20:42:02.879024,bot waked up
26.10.2018,20:48:27.176880,bot returned response
26.10.2018,22:45:23.750127,bot waked up
26.10.2018,22:45:27.292114,bot returned response
26.10.2018,22:45:39.876092,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,22:45:39.877074,bot restart attempt
26.10.2018,22:45:40.662233,bot waked up
26.10.2018,22:45:57.345833,bot was interrupted by error:local variable 'result' referenced before assignment in main
26.10.2018,22:45:57.345833,bot restart attempt
26.10.2018,22:45:58.271615,bot waked up
26.10.2018,22:46:29.988407,bot returned response
26.10.2018,22:54:06.212036,bot waked up
26.10.2018,22:54:43.723748,bot returned response
26.10.2018,22:57:47.597783,bot waked up
26.10.2018,23:15:55.002072,bot returned response
26.10.2018,23:16:01.343872,bot returned response
27.10.2018,01:37:45.693483,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
27.10.2018,01:37:45.694468,bot restart attempt
27.10.2018,01:37:46.571705,bot waked up
27.10.2018,12:08:24.321420,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
27.10.2018,12:08:24.321420,bot restart attempt
27.10.2018,12:08:25.205195,bot waked up
27.10.2018,18:46:05.892695,bot returned response
27.10.2018,18:46:40.957155,bot returned response
27.10.2018,18:47:43.301874,bot returned response
27.10.2018,18:48:13.609492,bot returned response
27.10.2018,18:48:25.311643,bot returned response
27.10.2018,18:48:56.014767,bot returned response
27.10.2018,18:56:27.880004,bot was interrupted by error:local variable 'result' referenced before assignment in main
27.10.2018,18:56:27.880983,bot restart attempt
27.10.2018,18:56:28.763794,bot waked up
27.10.2018,18:58:25.857621,bot waked up
27.10.2018,18:58:42.679795,bot was interrupted by error:local variable 'result' referenced before assignment in main
27.10.2018,18:58:42.679795,bot restart attempt
27.10.2018,18:58:43.459101,bot waked up
27.10.2018,19:05:28.310664,bot returned response
27.10.2018,19:05:44.610472,bot returned response
27.10.2018,19:06:49.270625,bot returned response
27.10.2018,19:06:56.868283,bot returned response
27.10.2018,19:07:48.348761,bot returned response
27.10.2018,19:08:26.150507,bot returned response
27.10.2018,19:09:21.075317,bot waked up
27.10.2018,19:20:39.107542,bot returned response
27.10.2018,19:25:36.439572,bot returned response
27.10.2018,19:26:18.867307,bot returned response
27.10.2018,19:53:06.808719,bot waked up
27.10.2018,19:53:59.240371,bot returned response
27.10.2018,19:56:03.229610,bot waked up
27.10.2018,19:56:41.585082,bot returned response
27.10.2018,19:57:18.207154,bot waked up
27.10.2018,20:08:01.654415,bot waked up
27.10.2018,20:13:55.416138,bot returned response
27.10.2018,20:13:59.673951,bot was interrupted by error:Unable to send due to closed RTM websocket in main
27.10.2018,20:13:59.673951,bot restart attempt
27.10.2018,20:14:00.648550,bot waked up
27.10.2018,20:14:24.512815,bot returned response
27.10.2018,20:14:50.680950,bot returned response
27.10.2018,20:55:15.861449,bot waked up
27.10.2018,20:56:12.279410,bot returned response
27.10.2018,21:04:06.043086,bot returned response
27.10.2018,21:05:05.609492,bot waked up
27.10.2018,21:05:23.276487,bot returned response
27.10.2018,21:05:46.581166,bot returned response
27.10.2018,21:06:12.588989,bot returned response
27.10.2018,21:06:59.862433,bot waked up
27.10.2018,21:07:32.288202,bot returned response
27.10.2018,21:08:19.022586,bot waked up
27.10.2018,21:08:50.063768,bot returned response
27.10.2018,21:09:44.453252,bot returned response
27.10.2018,21:10:28.838011,bot returned response
27.10.2018,21:11:06.756105,bot returned response
27.10.2018,21:13:10.710082,bot waked up
27.10.2018,21:13:44.254995,bot returned response
27.10.2018,21:14:55.818476,bot waked up
27.10.2018,21:15:22.333150,bot returned response
27.10.2018,21:15:53.590043,bot returned response
27.10.2018,21:17:16.470821,bot waked up
27.10.2018,21:17:46.419064,bot returned response
27.10.2018,21:22:51.667118,bot waked up
27.10.2018,21:23:23.229624,bot returned response
27.10.2018,21:27:20.505979,bot waked up
27.10.2018,21:27:42.709101,bot waked up
27.10.2018,21:28:03.587028,bot returned response
27.10.2018,21:29:04.106562,bot returned response
27.10.2018,21:30:52.775507,bot returned response
27.10.2018,21:34:05.680792,bot returned response
27.10.2018,21:36:03.482542,bot returned response
27.10.2018,21:37:22.928835,bot waked up
27.10.2018,21:37:52.880004,bot returned response
27.10.2018,21:38:48.625114,bot returned response
27.10.2018,21:39:56.906369,bot waked up
27.10.2018,21:40:05.442501,bot returned response
27.10.2018,21:40:30.536244,bot returned response
27.10.2018,21:41:25.500122,bot returned response
27.10.2018,23:16:31.495201,bot waked up
27.10.2018,23:16:51.060624,bot returned response
27.10.2018,23:16:56.347734,bot returned response
27.10.2018,23:17:20.047928,bot returned response
27.10.2018,23:17:38.366290,bot returned response
27.10.2018,23:18:07.067460,bot returned response
27.10.2018,23:18:36.679768,bot returned response
27.10.2018,23:18:49.968826,bot returned response
27.10.2018,23:19:05.560622,bot returned response
27.10.2018,23:19:20.179765,bot returned response
27.10.2018,23:19:32.786212,bot returned response
27.10.2018,23:19:53.084057,bot returned response
27.10.2018,23:20:07.733477,bot returned response
27.10.2018,23:20:35.860431,bot returned response
27.10.2018,23:21:20.963943,bot returned response
27.10.2018,23:24:12.857498,bot waked up
27.10.2018,23:25:03.909257,bot returned response
27.10.2018,23:25:59.446363,bot was interrupted by error:local variable 'result' referenced before assignment in main
27.10.2018,23:25:59.446363,bot restart attempt
27.10.2018,23:26:00.306718,bot waked up
27.10.2018,23:27:44.480550,bot returned response
27.10.2018,23:28:23.168051,bot returned response
27.10.2018,23:29:43.138744,bot returned response
28.10.2018,02:04:47.803783,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
28.10.2018,02:04:47.803783,bot restart attempt
28.10.2018,02:04:48.657310,bot waked up
28.10.2018,06:12:17.848473,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
28.10.2018,06:12:17.848473,bot restart attempt
28.10.2018,06:12:18.787941,bot waked up
28.10.2018,10:31:33.391449,bot returned response
28.10.2018,10:32:08.996918,bot returned response
28.10.2018,10:32:38.628751,bot returned response
28.10.2018,10:33:37.297694,bot returned response
28.10.2018,10:34:07.741053,bot returned response
28.10.2018,15:59:36.458833,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
28.10.2018,15:59:36.459806,bot restart attempt
28.10.2018,15:59:37.402197,bot waked up
29.10.2018,12:39:15.486433,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
29.10.2018,12:39:15.486433,bot restart attempt
29.10.2018,12:39:16.381945,bot waked up
30.10.2018,08:03:29.462994,bot was interrupted by error:can only concatenate str (not "NoneType") to str in main
30.10.2018,08:03:29.463970,bot restart attempt
30.10.2018,08:03:30.335063,bot waked up
30.10.2018,19:43:08.540623,bot waked up
30.10.2018,19:43:17.113378,bot returned response
30.10.2018,19:47:44.239361,bot waked up
30.10.2018,19:48:20.890725,bot returned response
30.10.2018,19:49:09.556750,bot returned response
30.10.2018,19:49:51.459077,bot was interrupted by error:can only concatenate str (not "NoneType") to str in main
30.10.2018,19:49:51.459077,bot restart attempt
30.10.2018,19:49:52.286229,bot waked up
30.10.2018,19:50:53.729590,bot waked up
30.10.2018,19:51:23.668067,bot returned response
30.10.2018,20:05:40.685648,bot waked up
30.10.2018,20:05:53.408302,bot returned response
30.10.2018,20:06:04.710066,bot returned response
30.10.2018,20:07:02.606553,bot returned response
30.10.2018,20:07:30.624124,bot returned response
30.10.2018,20:08:39.220812,bot was interrupted by error:local variable 'result' referenced before assignment in main
30.10.2018,20:08:39.220812,bot restart attempt
30.10.2018,20:08:40.088005,bot waked up
30.10.2018,20:09:33.155369,bot returned response
30.10.2018,20:09:46.489356,bot returned response
30.10.2018,20:21:22.026467,bot waked up
30.10.2018,20:21:31.663187,bot returned response
30.10.2018,20:21:54.543069,bot returned response
30.10.2018,20:25:01.387790,bot returned response
30.10.2018,20:28:28.375103,bot waked up
30.10.2018,20:28:41.088964,bot returned response
01.11.2018,07:03:36.943449,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
01.11.2018,07:03:36.944435,bot restart attempt
01.11.2018,07:03:37.834079,bot waked up
01.11.2018,09:14:05.960056,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
01.11.2018,09:14:05.960056,bot restart attempt
01.11.2018,09:14:06.875098,bot waked up
01.11.2018,14:29:03.484472,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
01.11.2018,14:29:03.484472,bot restart attempt
01.11.2018,14:29:04.480572,bot waked up
03.11.2018,02:14:38.855566,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
03.11.2018,02:14:38.856539,bot restart attempt
03.11.2018,02:14:39.857514,bot waked up
03.11.2018,11:25:24.675864,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
03.11.2018,11:25:24.675864,bot restart attempt
03.11.2018,11:25:25.573338,bot waked up
03.11.2018,15:01:03.613371,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
03.11.2018,15:01:03.614348,bot restart attempt
03.11.2018,15:01:04.480572,bot waked up
05.11.2018,09:32:39.192830,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
05.11.2018,09:32:39.192830,bot restart attempt
05.11.2018,09:32:40.238745,bot waked up
05.11.2018,18:28:36.653785,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
05.11.2018,18:28:36.653785,bot restart attempt
05.11.2018,18:28:37.588343,bot waked up
06.11.2018,02:51:34.554159,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
06.11.2018,02:51:34.554159,bot restart attempt
06.11.2018,02:51:35.529752,bot waked up
07.11.2018,02:32:04.307088,bot was interrupted by error:Unable to send due to closed RTM websocket in main
07.11.2018,02:32:04.307088,bot restart attempt
07.11.2018,02:32:05.248505,bot waked up
07.11.2018,02:47:10.301226,bot was interrupted by error:Unable to send due to closed RTM websocket in main
07.11.2018,02:47:10.301226,bot restart attempt
07.11.2018,02:47:11.200649,bot waked up
07.11.2018,02:59:52.157677,bot was interrupted by error:Unable to send due to closed RTM websocket in main
07.11.2018,02:59:52.158662,bot restart attempt
07.11.2018,02:59:53.088346,bot waked up
07.11.2018,08:35:38.255351,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
07.11.2018,08:35:38.255351,bot restart attempt
07.11.2018,08:35:39.241667,bot waked up
07.11.2018,12:42:27.379352,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
07.11.2018,12:42:27.379352,bot restart attempt
07.11.2018,12:42:48.968225,bot failed to connect
07.11.2018,12:42:49.957487,bot waked up
07.11.2018,23:31:50.013144,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
07.11.2018,23:31:50.013144,bot restart attempt
07.11.2018,23:31:50.839319,bot waked up
08.11.2018,02:47:25.449663,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
08.11.2018,02:47:25.449663,bot restart attempt
08.11.2018,02:47:26.279748,bot waked up
08.11.2018,12:34:08.426231,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
08.11.2018,12:34:08.426231,bot restart attempt
08.11.2018,12:34:09.440880,bot waked up
08.11.2018,15:26:20.017051,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
08.11.2018,15:26:20.017051,bot restart attempt
08.11.2018,15:26:21.092251,bot waked up
08.11.2018,21:55:45.247513,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
08.11.2018,21:55:45.247513,bot restart attempt
08.11.2018,21:55:46.198691,bot waked up
09.11.2018,00:26:43.151811,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.11.2018,00:26:43.151811,bot restart attempt
09.11.2018,00:26:44.121543,bot waked up
09.11.2018,02:30:20.083455,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.11.2018,02:30:20.083455,bot restart attempt
09.11.2018,02:30:21.112767,bot waked up
09.11.2018,06:58:05.119599,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
09.11.2018,06:58:05.119599,bot restart attempt
09.11.2018,06:58:07.083455,bot waked up
10.11.2018,08:49:00.708447,bot was interrupted by error:Unable to send due to closed RTM websocket in main
10.11.2018,08:49:00.709430,bot restart attempt
10.11.2018,08:49:01.617630,bot waked up
10.11.2018,12:59:56.000440,bot was interrupted by error:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение in main
10.11.2018,12:59:56.001426,bot restart attempt
10.11.2018,12:59:56.941850,bot waked up